### ISSUE TITLE
能否给个完整的实例

### ISSUE THREAD

**Issue by yexiaoxiao** [Vuchan/wx-ble#10]
大神的项目写的好完善，非常符合需求，就是demo写的好简单啊，看了大半天还是不大会用。
主要问题：蓝牙搜索到展现在页面之后如何跟其中的某个蓝牙交互（连接，收发数据）
能不能给个详细点的demo呀，773264939@qq.com，拜托拜托

**Comment by Vuchan** [comment]
注意邮箱，欢迎PR。
