### ISSUE TITLE
请教下Bluetooth is not defined问题

### ISSUE THREAD

**Issue by WhoIsAA** [vuchan/wx-ble#11]
你好，我用第二个方式先下载到本地utils/bluetooth目录，可是导入后找不到Bluetooth类，这个要怎么解决吗？以下是我的目录以及代码运行结果的截图，如若太忙可以联系邮箱：184696326@qq.com，感谢您的开源代码~
![Image text](http://oz12oj1xr.bkt.clouddn.com/WX20180810-204552@2x.png)
![Image text](http://oz12oj1xr.bkt.clouddn.com/WX20180810-204510@2x.png)
![Image text](http://oz12oj1xr.bkt.clouddn.com/Screenshot_20180810-204151.jpg)

**Comment by Vuchan** [comment]
1. 请检查你的路径，你的文件目录是：
```
pages
   /arduino
      /arduino
utils
   /bluetooth
      -index.js
```

所以你引入的时候，在 `pages/arduino/arduino/${name}.js`文件中应该如下：

```
import Bluetooth from '../../utils/bluetooth/index.js'
```

感觉是正确的啊。

2. 可以`bluetooth/index.js`文件中打个断点`debugger`，看在`import`执行时能否进入。

**Comment by feelkit** [comment]
我也遇到了同样的问题，为何？
