### ISSUE TITLE
如何找到目标设备？

### ISSUE THREAD

**Issue by meishaoming** [Vuchan/wx-ble#2]
你好，

读了一下你的代码，对发现目标设备这里的操作流程有些疑问。代码里的流程是：

1. 获取已连接设备列表。在列表中过滤，过滤条件是：name, localName, UUIDs
2. 如果上一步没找到，则开启 Discovery 搜索

第 1 步中，对于「目标设备」的过滤条件，我觉得有些不够，理由是：

1. 如果设备广播的 name/localName 都一样，则名字无法作为目标设备查找的充分条件
2. iOS 获得的 deviceId 是 uuid，Android 获取到的 deviceId 是 MAC 地址。一套代码分别运行于 Android 或 iOS 时所得到的结果不一样。

我对于找到「目标设备」的想法是：

1. 设备在广播附带数据 advertisData 中附带 MAC 地址，以此作为设备的唯一标志。在 Discovery 搜索时以此 MAC 地址作为过滤条件，即可找到目标设备。但 advertisData 在已连接设备列表中无法获取，此时这个方法不适用。
2. 在设备的服务列表中，将 MAC地址放入某个特征值里。对于已连接设备列表，逐个连接列表里的设备，并获取特征值，匹配目标的 MAC 地址。这样可以找到目标设备，但是需要多连接和读特征值两个操作。

希望与你讨论这个问题。

**Comment by GivingWu** [comment]
你好，首先向你的建议表达诚挚的谢意。

由于我的疏忽，忘了这一点：设备广播的 name/localName 都一样这种情况。😅*3
因此对于「目标设备」的逻辑判断的确存在你所描述的问题。

同时，为我晚了8个小时的回复表示抱歉。

**Comment by GivingWu** [comment]
由于最近项目原因，我可能在周末时才能拿出时间来维护。
如果其影响了你的开发任务的话，向你致歉同时欢迎你的P/R。

至于其相关技术的讨论，你可以回复我的comment，谢谢。

**Comment by Vuchan** [comment]
我最近工作比较忙，无法跟你讨论。希望你的实验顺利。

**Comment by Vuchan** [comment]
如果 deviceName 广播一致，剩下一个简单粗暴的方法便是对比 deviceId ？不是吗？
所以:
```js
 if (device.deviceName === deviceName && device..deviceId === deviceId) {}
```

这种理论上而言，是可以处理大部分deviceName同名情况的。

**Comment by meishaoming** [comment]
明白你的意思。但我理解设备工作时的广播 UUID 应该全都是一样的。

「如何找到目标设备」这件事非常依赖于硬件设备的蓝牙工作方式。这个问题并没有一个标准答案，但或许可以讨论出一两个最佳实践。

对于蓝牙硬件设备，我知道的有两种常规做法：

1. 每个蓝牙设备广播的设备名不同。比如摩拜单车后期上了蓝牙方案的锁就是这种做法。使用蓝牙扫描软件可以扫描出附近所有的蓝牙设备。每个设备名里包含设备的唯一ID。这种做法的缺点是扫描得出的设备名会看起来很怪异。

2. 在广播的 Manufacturer 字段放置设备的唯一 ID。比如 iBeacon 协议里就在该字段里放置了设备的 MAC 地址。扫描到广播之后，分析广播中的数据就知道该蓝牙设备是谁了。

我之前提的问题是上面 2 的实现，在微信小程序里不知道怎么搞比较方便。因为我用 Android 设备来测试，发现了 getConnectedBluetoothDevices 只能返回设备名和 deviceId，无法获取到广播数据。

后来测试之后，发现是我用错接口了。对于 Android 设备，已经被扫描到的设备都可以用 wx.getBluetoothDevices 接口获取到，并且还可以拿到广播数据字段。使用这个来过滤设备就可以了。

**Comment by Vuchan** [comment]
what can i say?  man. So professional.

给你点赞。👍
