### ISSUE TITLE
状态转换错误

### ISSUE THREAD

**Issue by OneWolfgang** [Vuchan/wx-ble#3]
我在用小程序调试蓝牙设备时，在连接成功后出现如下的错误：
trigger.js? [sm]:42 TypeError: Cannot read property 'notifyId' of undefined
    at notifyBLECharacteristicValueChange (transfer.js? [sm]:19)
    at Bluetooth.transfer (transfer.js? [sm]:29)
    at Bluetooth.exec (trigger.js? [sm]:32)
    at Bluetooth.changeState [as trigger] (trigger.js? [sm]:24)
    at Function.<anonymous> (search.js? [sm]:47)
    at [publib]:3
    at Function.<anonymous> ([publib]:9)
    at [publib]:4
    at Object.S ([publib]:1)
    at Object.value [as subscribeHandler] ([publib]:757) "W-TGR:at action:function transfer(isValid) {

请问这个是什么原因呢？

**Comment by Vuchan** [comment]
[这一行的问题](https://github.com/Vuchan/wx-ble/blob/master/states/transfer.js#L19)
```js
characteristicId: self._characteristic.notifyId,
```

表明 `self._characteristic` 中没有 `notifyId` 这个属性。[more](https://github.com/Vuchan/wx-ble/blob/master/index.js#L177)，如果这行没有报错的话，那么

```js
 if (notify) this._characteristic.notifyId = uuid
```

微信的API可能一直在更新，因此建议您在：
```js
function notifyBLECharacteristicValueChange() {
   console.log(self._device, selft._characteristic); // debugger on this line
    self.notifyBLECharacteristicValueChange({
      deviceId: self._device.deviceId,
      serviceId: self._serviceId,
      characteristicId: self._characteristic.notifyId,
      state: true
    }).then(_ => {
      setTimeout(_ => {
        self.onBLECharacteristicValueChange(onBLECharacteristicValueChange.bind(self))
        onConnect && isFunction(onConnect) && onConnect.call(self)
      }, 1000)
    }).catch(error => self.trigger('failure', error, notifyBLECharacteristicValueChange))
  }
```

**Comment by OneWolfgang** [comment]
现在不出现这个错误，但是每次都是连接失败，我用其他的小程序蓝牙工具可以连接上，用这个代码就连接不上：

W-BLE:response:  {isDiscovering: true, errCode: 0, errMsg: "startBluetoothDevicesDiscovery:ok"}
promiseify.js? [sm]:119 W-BLE:'wx.onBluetoothDeviceFound' be called.
init.js? [sm]:13 W-BLE:into bluetoothStateHandler  {available: true, discovering: true}
index.js? [sm]:74 W-BLE:Current state is search
index.js? [sm]:41 Sorry, current bluetooth JDY-16 connect timeout.
index.js? [sm]:45 Sorry, current bluetooth JDY-16 connect fail. Error info undefined
index.js? [sm]:228 W-BLE: into this.resetState(), Bluetooth instance numbers:  0
promiseify.js? [sm]:87 W-BLE:into request method:  closeBluetoothAdapter
promiseify.js? [sm]:89 W-BLE:response:  {errMsg: "closeBluetoothAdapter:ok"}

**Comment by Vuchan** [comment]
看你贴的代码是因为 `timeout` 的原因，一旦在特定延时时间内没有连接成功，就会挂掉。

```js
index.js? [sm]:41 Sorry, current bluetooth JDY-16 connect timeout.
index.js? [sm]:45 Sorry, current bluetooth JDY-16 connect fail. Error info undefined
```

[source method](https://github.com/Vuchan/wx-ble/blob/master/index.js#L62)

抱歉，可能因为我的 [timeout](https://github.com/Vuchan/wx-ble/blob/master/readme.md#config) 在 config.js 中 default value 是 6 秒，但是我却在 Readme 中写成了10秒，我应该默认关闭这个 opiton。

timeout | Number |   | 10 | 以s(秒)为单位。如果为0，则关闭该项。在蓝牙的连接过程中，若在该 timeout秒时间内无法连接，则进入 timeout 回调。

**Comment by OneWolfgang** [comment]
我测试发现好像不是超时的原因，超时设置多久都无法建立连接。

**Comment by Vuchan** [comment]
抱歉，可能是误操作导致，这个 `issue` 的处理**很不及时**。
不知道你的问题是否已经解决？

从 console 上来看，没有看到 进入 `connect` state 的 debugg 呢？
如果问题比较急，请发邮件至 `givingwu@gmail.com`。
