### ISSUE TITLE
请问有没有具体的使用流程呢？

### ISSUE THREAD

**Issue by dearxd** [Vuchan/wx-ble#5]

**Comment by Vuchan** [comment]
什么叫做具体的使用流程？
[example](https://github.com/Vuchan/wx-ble/blob/master/readme.md#example)
这个 demo 算吗？
应该是你根据你的业务场景来配置，对吗？

**Comment by dearxd** [comment]
您好有对应的demo下，使用您提供的这个蓝牙插件嘛？最近在搞这个微信小程序蓝牙功能，根据官方的API和网上的例子，做到了wx.notifyBLECharacteristicValueChange返回蓝牙设备的二进制数，代码写的不规范，只能算是测试下功能，之前也没有搞过蓝牙这块，看硬件给的文档有点蒙，对应的字节代表啥，然后根据二进制如何去换算一脸懵逼，我的邮箱是 15022533697@163.com，

**Comment by Vuchan** [comment]
我只能给你我之前的demo，可以晚上在业余时间邮件沟通细节。😊

**Comment by dearxd** [comment]
![Uploading image.png…]()
您好，我按照你这个例子，我这样子引用报错为非法构造函数
WAService.js:3 thirdScriptError
Illegal constructor;at pages/newIndex/newIndex page lifeCycleMethod onLoad function
TypeError: Illegal constructor

**Comment by dearxd** [comment]
那麻烦您帮我看一下我调用你这个插件报错是哪里的原因呢，上面的截图第一个是。

**Comment by Vuchan** [comment]
E-mail
