### ISSUE TITLE
能否在一个实际的例子中讲解一下使用方法呢

### ISSUE THREAD

**Issue by cityO** [Vuchan/wx-ble#6]
非常惊喜的在GitHub中发现了这个项目, 最近在做小程序蓝牙相关的功能,只是大神的例子好高深,小白有些看不懂,不知可否在一个简单的可以在小程序里体验的demo中讲解讲解,谢谢

**Comment by Vuchan** [comment]
1. 你好，首先谢谢你讲到的惊喜，同时希望这个项目对你有实质性的帮助。
2. 我曾收到类似 issue 的邮件。这个是你的邮件吗？wangsfox@foxmail.com 我把早期的demo发给你邮件了。
