### ISSUE TITLE
连接蓝牙打印机提示connect timeout，大神给指点一下看什么问题

### ISSUE THREAD

**Issue by hnlyd** [Vuchan/wx-ble#7]
配置：
<img width="639" alt="_20180412122112" src="https://user-images.githubusercontent.com/26771555/38656274-0678b9bc-3e4c-11e8-9b57-bd807313d452.png">

结果：
<img width="784" alt="default" src="https://user-images.githubusercontent.com/26771555/38656232-bafdd33c-3e4b-11e8-8b03-5206423f1c1b.png">

**Comment by Vuchan** [comment]
你设置了 `timeout: 5`，所以如果 5s 内连接失败，就会抛出 timeout 的错误。
